language: java
script: mvn test
jdk:
- openjdk7
branches:
  only:
  - devel
env:
  global:
  - secure: CB9V3CmnZRuNapNI8QYEO+tawsvqgEqLOM1FoIjHiPf2bMdmjud0dwcQWNuiMJzWR0FJaARvqQWmndP7SePNUaeIkkRoGJ0InmIrXwWtvGq/YKdxEWC8JpMxeONjKNZ6w1LhtRHpHKDxa9P1EgvyDMtg9pPIgDtoab86lXCK+2A=
  - secure: HCRUaOrwfMQQgtlFI5iKEa1CAKmf9R6GgifIpIjgLERgzxTzn3hJQkR9GvVpqB5Vo/50mCQM07LI6wB/Q9yI5b9d3M4Ey9RJebRRiHSvUyoOG8/tYHmZ8rphDVqInJSFDDcjHkGWI4KbPCe9cFvIuXhqWKensUEOl9WDFKDl4Uw=
before_install:
- unset GEM_PATH
after_success:
- python travis-prepare-maven.py
- mvn deploy --settings ~/.m2/mySettings.xml
notifications:
  irc:
    channels:
    - chat.freenode.net#otavanopisto-muikku
    use_notice: true
    skip_join: true
    template:
    - '%{repository} (%{commit}) : %{message} %{foo} '
    - 'Build details: %{build_url}'
  webhooks:
    urls: 
    - http://build.staging.fi/travis.php
    on_success: always
    on_failure: never
    on_start: false
