# Language 

language: java

# Maven 
script: mvn test
  
# JDK versions
jdk:
  - openjdk7

# whitelist devel
branches:
  only:
    - devel

# Global environment variables
env:
  global:
    - secure: "CB9V3CmnZRuNapNI8QYEO+tawsvqgEqLOM1FoIjHiPf2bMdmjud0dwcQWNuiMJzWR0FJaARvqQWmndP7SePNUaeIkkRoGJ0InmIrXwWtvGq/YKdxEWC8JpMxeONjKNZ6w1LhtRHpHKDxa9P1EgvyDMtg9pPIgDtoab86lXCK+2A="
    - secure: "HCRUaOrwfMQQgtlFI5iKEa1CAKmf9R6GgifIpIjgLERgzxTzn3hJQkR9GvVpqB5Vo/50mCQM07LI6wB/Q9yI5b9d3M4Ey9RJebRRiHSvUyoOG8/tYHmZ8rphDVqInJSFDDcjHkGWI4KbPCe9cFvIuXhqWKensUEOl9WDFKDl4Uw="

# Fix for See https://github.com/Jasig/sass-maven-plugin/issues/47
before_install:
  - unset GEM_PATH

# Prepare maven, deploy artifacts and update staging server
# -Dmaven.test.skip is because integration tests install container and
# run browser; both are a bad idea on a build server
after_success:
  - python travis-prepare-maven.py
  - mvn deploy --settings ~/.m2/mySettings.xml

# Notifications 
notifications:
  irc:
    channels:
      - "chat.freenode.net#otavanopisto-muikku"
    use_notice: true
    skip_join: true
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
