language: java
script: mvn install
# See https://github.com/Jasig/sass-maven-plugin/issues/47
before_install:
  - unset GEM_PATH
jdk:
  - oraclejdk7
  - openjdk7

# whitelist
branches:
  only:
    - devel
    
after_success:
  - mvn package -f muikku/pom.xml -Popenshift
before_deploy: "Ready for DEPLOYMENT????"  
deploy:
  provider: openshift
  user:
    secure: "IULca5XuovOnLRrgL6VBzwcAs4u1cxL6AMMpLFovCc4+aFw1N29mPMGMc1mmLSI51cn2FRGcbc7J+MZHPrtL6c215X5KdBjMVIJxyoJq8ZRzrXfHfbmhgZLNG6BvLjKocH9sQXFdTY4zHi+GafeSFFUzdZnMMrHoBmCiAozbOLI="
  password:
    secure: "Y9yuZuoc8Mx4NQSsPpOC0JbmrTVy4LhQZt9iuPK+YAoIHi0TlpYwTY8ewQSJrMziyfQoHd9+lEU/T2kl0ll9njf94QlBAKrmqSW5H11xqQ7VJIPNQqxxcc2aAQD0NOwtV52OJ3e1FKzlkT/jpvHMBreEOY/6xnwADUf0uccJw6M="
  app: muikku
  domain: oodev
  on:
    jdk: openjdk7
    branch: devel
after_deploy: "I have deployed"