language: java
# See https://github.com/Jasig/sass-maven-plugin/issues/47
before_install:
  - unset GEM_PATH
jdk:
  - oraclejdk7
  - openjdk7
env:
  global:
    - secure: "IULca5XuovOnLRrgL6VBzwcAs4u1cxL6AMMpLFovCc4+aFw1N29mPMGMc1mmLSI51cn2FRGcbc7J+MZHPrtL6c215X5KdBjMVIJxyoJq8ZRzrXfHfbmhgZLNG6BvLjKocH9sQXFdTY4zHi+GafeSFFUzdZnMMrHoBmCiAozbOLI="
    - secure: "Y9yuZuoc8Mx4NQSsPpOC0JbmrTVy4LhQZt9iuPK+YAoIHi0TlpYwTY8ewQSJrMziyfQoHd9+lEU/T2kl0ll9njf94QlBAKrmqSW5H11xqQ7VJIPNQqxxcc2aAQD0NOwtV52OJ3e1FKzlkT/jpvHMBreEOY/6xnwADUf0uccJw6M="

deploy:
  provider: openshift
  user: OPENSHIFT_USER
  password: OPENSHIFT_PASSWORD
  domain: oodev

# whitelist
branches:
  only:
    - devel